#cosmost-server-url.board=http://localhost:8081
#cosmost-server-url.popularity=http://localhost:8082

server:
  port: 9000

spring:
  application:
    name: cosmost-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
          allowedOrigins: "http://localhost:3000"
          allow-credentials: true
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v1/auths/**, /v1/view/**, /v1/signin, /v1/validation/**,
              /v1/authorization/**, /auth-service/**

        - id: cosmost-service
          uri: lb://COSMOST-SERVICE
          predicates:
            - Path=/v1/cosmosts/**, /v1/view/**, /cosmost-service/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/v1/comments/**, /v1/view/**, /comment-service/**

        - id: popularity-service
          uri: lb://POPULARITY-SERVICE
          predicates:
            - Path=/v1/popularities/**, /pupularity-service/**

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/v1/boards/**, /board-service/**

token:
  expiration_time: 86400000
  secret: user_token
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
